name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
          semgrep -e p/r2c/python-all --lang=python .
      
    - name: Run Semgrep
      run: |
            semgrep -e p/r2c/python-all --lang=python --json > semgrep_results.json
        
